version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     
     # build the application 
     - run: cat /etc/docker/daemon.json 
     - run: docker version
     - run: docker build -t company/app:test .
     
