version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     
     # Install JFrog CLI
     - run: curl -fL https://getcli.jfrog.io | sh
     
     # Configure Artifactory instance with JFrog CLI
     #- ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_PASSWORD --interactive=false
     
     # build the application 
     - run: curl -uadmin:password -O http://13.229.71.253:8081/artifactory/maven-dev-local/org/jfrog/test/multi3/3.7-SNAPSHOT/multi3-3.7-20191219.073052-2.war
     - run: ls -l
     - run: echo "13.229.71.253 www.testexample.com" >> /etc/hosts
     - run: cat /etc/hosts
     #- run: docker login -u admin -p password 13.229.71.253:8081
     
     #- run: docker build -t 13.229.71.253:8081/docker-virtual/app:latest .
     
     #- run: docker push 13.229.71.253:8081/docker-virtual/app:latest
     
     #- docker build -t $ARTIFACTORY_DOCKER_REPOSITORY/maven-version:$CIRCLE_BUILD_NUM .
     #- docker login -e $ARTIFACTORY_EMAIL -u $ARTIFACTORY_USER -p $ARTIFACTORY_PASSWORD $ARTIFACTORY_DOCKER_REPOSITORY
     #- ./jfrog rt dp $ARTIFACTORY_DOCKER_REPOSITORY/maven-version:$CIRCLE_BUILD_NUM docker-virtual --build-name=circleci-docker-artifactory --build-number=$CIRCLE_BUILD_NUM
     #- ./jfrog rt bce circleci-docker-artifactory $CIRCLE_BUILD_NUM
     #- ./jfrog rt bp circleci-docker-artifactory $CIRCLE_BUILD_NUM
     
     
