version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     
     # build the application 
     - run: curl -uadmin:password -O http://13.229.71.253:8081/artifactory/maven-dev-local/org/jfrog/test/multi3/3.7-SNAPSHOT/multi3-3.7-20191219.073052-2.war

     - run: docker build -t 13.229.71.253:8081/docker-virtual/app:test .
     
